image: node:latest

cache:
  paths:
    - node_modules/


pages:
  stage: deploy
  script:
    - npm install
    - mkdir public
    - npx babel labs.js --presets=env | npx uglifyjs -o public/labs-polyfill.min.js
  artifacts:
    paths:
      - public
  only:
  - /^staging\/.*$/
